

analyzer:
  errors:
    unused_catch_clause: ignore
    unnecessary_null_comparison: ignore

linter:
  rules:
    # Las desactivas poniéndolas en false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    # Y así sucesivamente con cada lint que quieras quitar
